# Automatically generated by SST
# pylint: disable=all
from typing import Any

class Resource:
    class App:
        name: str
        stage: str
    class BatchProtAPI:
        name: str
        type: str
        url: str
    class MyPostgres:
        database: str
        host: str
        password: str
        port: float
        type: str
        username: str
    class MyVpc:
        type: str
    class MyWeb:
        type: str
        url: str

