// This file is auto-generated by @hey-api/openapi-ts

/**
 * AuthCheckResponse
 */
export type AuthCheckResponse = {
  /**
   * Message
   */
  message: string;
  /**
   * User Id
   */
  user_id: string;
};

/**
 * ErrorResponse
 */
export type ErrorResponse = {
  /**
   * Detail
   */
  detail: string;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
  /**
   * Detail
   */
  detail?: Array<ValidationError>;
};

/**
 * HealthCheckResponse
 */
export type HealthCheckResponse = {
  /**
   * Status
   */
  status: string;
};

/**
 * ProteinAnalysisRequest
 */
export type ProteinAnalysisRequest = {
  /**
   * Sequences
   */
  sequences: Array<string>;
};

/**
 * ProteinAnalysisResponse
 */
export type ProteinAnalysisResponse = {
  /**
   * Results
   */
  results: Array<ProteinAnalysisResult>;
};

/**
 * ProteinAnalysisResult
 */
export type ProteinAnalysisResult = {
  /**
   * Sequence
   */
  sequence: string;
  /**
   * Length
   */
  length: number;
  /**
   * Molecular Weight
   */
  molecular_weight: number;
  /**
   * Aromaticity
   */
  aromaticity: number;
  /**
   * Instability Index
   */
  instability_index: number;
  /**
   * Gravy
   */
  gravy: number;
  /**
   * Isoelectric Point
   */
  isoelectric_point: number;
  /**
   * Helix Fraction
   */
  helix_fraction: number;
  /**
   * Turn Fraction
   */
  turn_fraction: number;
  /**
   * Sheet Fraction
   */
  sheet_fraction: number;
  /**
   * Extinction Coeff Reduced
   */
  extinction_coeff_reduced: number;
  /**
   * Extinction Coeff Oxidized
   */
  extinction_coeff_oxidized: number;
  /**
   * Charge At Ph7
   */
  charge_at_ph7: number;
  /**
   * Amino Acid Counts
   */
  amino_acid_counts: {
    [key: string]: number;
  };
  /**
   * Amino Acid Percentages
   */
  amino_acid_percentages: {
    [key: string]: number;
  };
};

/**
 * ValidationError
 */
export type ValidationError = {
  /**
   * Location
   */
  loc: Array<string | number>;
  /**
   * Message
   */
  msg: string;
  /**
   * Error Type
   */
  type: string;
};

export type HealthReadRootData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/v1/health';
};

export type HealthReadRootResponses = {
  /**
   * Successful Response
   */
  200: HealthCheckResponse;
};

export type HealthReadRootResponse =
  HealthReadRootResponses[keyof HealthReadRootResponses];

export type AnalysisRunAnalysisData = {
  body: ProteinAnalysisRequest;
  path?: never;
  query?: never;
  url: '/api/v1/analyze';
};

export type AnalysisRunAnalysisErrors = {
  /**
   * Bad Request
   */
  400: ErrorResponse;
  /**
   * Unauthorized
   */
  401: ErrorResponse;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type AnalysisRunAnalysisError =
  AnalysisRunAnalysisErrors[keyof AnalysisRunAnalysisErrors];

export type AnalysisRunAnalysisResponses = {
  /**
   * Successful Response
   */
  200: ProteinAnalysisResponse;
};

export type AnalysisRunAnalysisResponse =
  AnalysisRunAnalysisResponses[keyof AnalysisRunAnalysisResponses];

export type AuthCheckAuthData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/v1/auth-check';
};

export type AuthCheckAuthErrors = {
  /**
   * Unauthorized
   */
  401: ErrorResponse;
};

export type AuthCheckAuthError = AuthCheckAuthErrors[keyof AuthCheckAuthErrors];

export type AuthCheckAuthResponses = {
  /**
   * Successful Response
   */
  200: AuthCheckResponse;
};

export type AuthCheckAuthResponse =
  AuthCheckAuthResponses[keyof AuthCheckAuthResponses];

export type ClientOptions = {
  baseUrl:
    | 'https://nfkxbhletrjyqsuq3jggydfrl40kmcyf.lambda-url.us-east-2.on.aws'
    | (string & {});
};
