// This file is auto-generated by @hey-api/openapi-ts

import { z } from 'zod';

/**
 * AuthCheckResponse
 */
export const zAuthCheckResponse = z.object({
  message: z.string(),
  user_id: z.string(),
});

/**
 * ErrorResponse
 */
export const zErrorResponse = z.object({
  detail: z.string(),
});

/**
 * ValidationError
 */
export const zValidationError = z.object({
  loc: z.array(z.union([z.string(), z.number().int()])),
  msg: z.string(),
  type: z.string(),
});

/**
 * HTTPValidationError
 */
export const zHttpValidationError = z.object({
  detail: z.array(zValidationError).optional(),
});

/**
 * HealthCheckResponse
 */
export const zHealthCheckResponse = z.object({
  status: z.string(),
});

/**
 * ProteinAnalysisRequest
 */
export const zProteinAnalysisRequest = z.object({
  sequences: z.array(z.string()),
  analysis_type: z.string().optional().default('basic'),
});

/**
 * ProteinAnalysisResult
 */
export const zProteinAnalysisResult = z.object({
  sequence: z.string(),
  length: z.number().int(),
  molecular_weight: z.number(),
  isoelectric_point: z.number(),
  aromaticity: z.union([z.number(), z.null()]).optional(),
  instability_index: z.union([z.number(), z.null()]).optional(),
  gravy: z.union([z.number(), z.null()]).optional(),
  helix_fraction: z.union([z.number(), z.null()]).optional(),
  turn_fraction: z.union([z.number(), z.null()]).optional(),
  sheet_fraction: z.union([z.number(), z.null()]).optional(),
  extinction_coeff_reduced: z.union([z.number().int(), z.null()]).optional(),
  extinction_coeff_oxidized: z.union([z.number().int(), z.null()]).optional(),
  charge_at_ph7: z.union([z.number(), z.null()]).optional(),
  amino_acid_counts: z.object({}),
  amino_acid_percentages: z.object({}),
});

/**
 * ProteinAnalysisResponse
 */
export const zProteinAnalysisResponse = z.object({
  results: z.array(zProteinAnalysisResult),
});

export const zHealthReadRootData = z.object({
  body: z.never().optional(),
  path: z.never().optional(),
  query: z.never().optional(),
});

/**
 * Successful Response
 */
export const zHealthReadRootResponse = zHealthCheckResponse;

export const zAnalysisRunAnalysisData = z.object({
  body: zProteinAnalysisRequest,
  path: z.never().optional(),
  query: z.never().optional(),
});

/**
 * Successful Response
 */
export const zAnalysisRunAnalysisResponse = zProteinAnalysisResponse;

export const zAuthCheckAuthData = z.object({
  body: z.never().optional(),
  path: z.never().optional(),
  query: z.never().optional(),
});

/**
 * Successful Response
 */
export const zAuthCheckAuthResponse = zAuthCheckResponse;
